### ISSUE TITLE
Branch-and-merge workflow vs Go absolute paths

### ISSUE THREAD

**Issue by bford** [DeDiS/crypto#12]
Crap, I *hate* how Go basically forces you to put absolute, global pathnames in every package in a large multi-package collection, just to allow one package in the collection to refer to another package in the same collection.  In particular, it seems like it perhaps fundamentally breaks the multi-branch, pull-request-oriented Github workflow for any change that involves multiple packages - or especially that involves adding new packages, as my current pull request does (https://github.com/DeDiS/crypto/pull/11).

In particular, the Travis CI script wants to build the version in my pull request, but when one package requires another new package added in the same pull request (e.g., crypto/subtle), it goes looking for the new package in the _original_ master repository at the global package address ("github.com/dedis/crypto/subtle"); it's of course not there, so of course Travis CI complains.

So to fix it looks like I have to "temporarily" change the global address of the referenced package in the pull-request version - but can't forget to change it back before actually merging, otherwise the master version of the library will end up incorrectly referring to packages in side-branches like my personal repo.   Ugh!!!

Does anyone know a good solution to this?  This must have caused a bunch of people significant amounts of pain by now.  Perhaps it's one major reason why the golang developers don't use the branch-and-merge workflow - but eliminating the possibility of using such a workflow seems like a really horrible thing for a language to do, in general.  Does anyone know if there's a facility in golang to force a temporary substitution of a top-level package name, e.g., to build a repository so as to pretend that "github.com/dedis/crypto/..." imports in the repo really mean "github.com/bford/crypto/..." just for the moment?  That would be a hack but would at least work around the problem.

Thanks
Bryan

**Comment by jackowitzd2** [comment]
Bryan,

Headaches with the imports was the main reason I used a branch within the original repository approach rather than a fork for the commits I pushed. You can still do pull requests as normal across branches, and Travis seems to handle it, running the build on the results of the merge (see travis-test branch pull request). It's not the typical GitHub workflow, since commiters all need repository write permissions, but may be worth considering.

Danny

**Comment by bford** [comment]
Thanks Danny for pointing out that solution, which is far from ideal but might work as a stopgap solution at least.  However, even that isn't quite working (yet) for me.  I created a new pull request based on another branch in the master repo (https://github.com/DeDiS/crypto/pull/15) - but the Travis CI failed there too.

Dylan: it looks like the 'go get -t -v' part of your script is failing because of packages that are new in the pull request but don't exist in the master branch.  See this log: https://travis-ci.org/DeDiS/crypto/builds/46777309

This is stupid because the referenced packages "should" be already there in the repository that Travis just checked out via the 'git clone' command at the top.  But perhaps 'go get' stupidly goes and tries to fetch all referenced packages before it even checks locally to see whether they're already there (perhaps it's trying to update them if they're out-of-date), and dies when it doesn't find them in the default (master) branch at the destination.  Can you find a workaround, e.g., is there a way to make 'go get' only try to fetch *external* dependencies (referring to other repositories) and not internal dependencies to other packages in the same repository?

**Comment by jackowitzd2** [comment]
Dylan: I think the ```go get -t -v ./...``` is from Travis itself, but it looks like you can override the way it fetches dependencies to ignore the internal ones. See http://docs.travis-ci.com/user/languages/go/.

**Comment by bford** [comment]
In the longer term, though, it would be really nice to have a "real" solution as well.  Does anyone know of, or can anyone find, any pointers to relevant discussion on the golang-nuts or golang-dev lists for example?  It feels like this must have been discussed (perhaps at length) already; supporting a decentralized branch-and-merge workflow just seems too basic not to have come up.  Anyone who can find any relevant discussion pointers, please post them.  If there's no adequate solution, I'm not opposed to coming up with a proposal and actually hacking Go if necessary.  

What I'd really like is just a way to make Go not quite so fascist about allowing local inter-package references, e.g., be able to import "../abstract" or "/crypto/abstract" instead of "github.com/dedis/crypto/abstract".  That really doesn't seem like too much to ask, does it?  Again, can anyone find any pointers to golang mailing list discussions or what not regarding this?

**Comment by bford** [comment]
Dylan, pull #16 apparently didn't (fully) fix the problem unfortunately; see the new results:

https://travis-ci.org/DeDiS/crypto/builds/46790875

I haven't tried to examine the details yet though.  Could you perhaps create a temporary copy of the 'cipher' branch and a pull request for testing/experimenting with it to get the CI system to work with it?  Thanks.

**Comment by bford** [comment]
Dylan, it's now closer to working - thanks.  At least it got far enough to run gofmt and give me a list of the source files that weren't gofmt-compliant, which is good.

But there's still an issue: apparently your ci-script code can't yet deal with source files being deleted.  See the latest travis results: https://travis-ci.org/DeDiS/crypto/builds/47000557  The 'abstract/stream.go' went away; your script included it in the list of "files changed", which is true, but then failed because 'stat abstract/stream.go' failed.  Please fix (should be trivial); thanks.

**Comment by bford** [comment]
Looks like the CI system is working well enough to grok the big cipher commit; thanks.

I would *still* like a "real" solution to the absolute-paths problem that doesn't require us to be restricted to using different branches in the same repo.  If anyone can find any info on that, please let me know.  But failing that, closing the thread for now; need to move on to real work.
