### ISSUE TITLE
State of Cipher.Stream

### ISSUE THREAD

**Issue by davidiw** [DeDiS/crypto#27]
What are the plans of Cipher.Stream? It would seem like it is more or less deprecated, but there are many instances that still depend on it.

https://github.com/DeDiS/crypto/blob/master/abstract/group.go#L53
https://github.com/DeDiS/crypto/blob/master/abstract/cipher.go#L80
https://github.com/DeDiS/crypto/blob/master/random/rand.go

If it is indeed deprecated, should these calls be ported to use cipher and Write instead?

**Comment by bford** [comment]
That is TBD; comments welcome.  The crypto library used to use the cipher.Stream interface extremely pervasively; as you can see it still uses it for quite a lot, although much of what it uses for could trivially be replaced with calls to the new abstract.Cipher API instead.  I'm not in a hurry to get rid of the cipher.Stream legacy compatibility - that functionality is certainly needed in any case, the question is just via what API - so it's probably not worth worry about a lot for now, and I don't think we need to start an aggressive campaign to replace code that uses cipher.Stream just yet.  It's probably worth waiting and making sure abstract.Cipher is (or becomes) mature enough before we try to use it directly for everything.

**Comment by bford** [comment]
P.S.  Toward that end - i.e., making sure abstract.Cipher is mature enough or getting it to that point, I'd *really* like someone to help by taking up this simple and fun work-item: https://github.com/DeDiS/crypto/issues/24

:)
