### ISSUE TITLE
Encoding Bytes Arrays

### ISSUE THREAD

**Issue by WEB3-GForce** [DeDiS/crypto#29]
@davidiw
@bford 
@jackowitzd2 

I am working with abstract.Write and abstract.Read encoding. I am attempting to encode a struct of the form:

type PolicyApprovedMessage struct {
	PubKey abstract.Point
	Message []byte
        Signature []byte
}

where Message is a string converted to a byte array and signature is a digital signature of the message. When I do the encoding:

	b := bytes.Buffer{}
	abstract.Write(&b, msg, KEY_SUITE)

and decoding
	b := bytes.NewBuffer(data)
	err := abstract.Read(b, msg, KEY_SUITE)

The public key comes out fine. However, the byte arrays are of length 0 when I decode. When I encode via encoding/gob, I am able to get my arrays back:

//	var b bytes.Buffer
//	enc := gob.NewEncoder(&b)
//	err := enc.Encode(msg.Message)
//	err = enc.Encode(msg.Signature)

//	b := bytes.NewBuffer(data)
//	dec := gob.NewDecoder(b)
///	err := dec.Decode(&msg.Message)
//	err = dec.Decode(&msg.Signature)

Am I simply not handling encoding of byte arrays properly, or is this an error with encoding? Could someone try encoding a byte array and seeing if they can reproduce this error?

**Comment by bford** [comment]
You shouldn't be using abstract.Read and abstract.Write for all-purpose encoding/decoding of variable-length or extensible messages and stuff like that - instead you should be using the protobuf package (https://github.com/DeDiS/protobuf).  The abstract.Read/Write mechanism is intended for and only works for encoding/decoding cryptographic objects of known-beforehand size and shape, which is often the case for cryptographic objects like digital signatures but isn't usually the case for larger protocol messages.

@jackowitzd2 has been working on the protobuf code and tells me he identified some compatibility issues that arose recently; perhaps he can comment further?

**Comment by dyv** [comment]
Look at the CommitmentMessage in signingMessages.go in the prifi/coco branch (preferably at the most recent information in the coco-refactor pull request). There you will see how we handle the same problem (hashid.HashId is a type alias for  []byte). Write is unable to handle variable length slices (at least from what we have observed). Therefore, for now, we write the bytes of our hashid.HashId everything works fine.

What I would suggest is something like the following code (untested and uncompiled):
```go
func (pam *PolicyApprovedMessage) MarshalBinary() ([]byte, error) {
    var b bytes.Buffer
    err := abstract.Write(&b, pam, pam.suite)
    if err != nil {
        return nil, err
    }
    enc := gob.NewEncoder(&b)
    err = enc.Encode(pam.Message)
    if err != nil {
        return nil, err
    }
    err = enc.Encode(pam.Signature)
    return b.Bytes(), err
}

func (pam *PolicyApprovedMessage) UnmarshalBinary(data []byte) error {
    b := bytes.NewBuffer(data)
    err := abstract.Read(b, pam, pam.suite)
    if err != nil {
        return err
    }
    dec := gob.NewDecoder(b)
    err = dec.Decode(&pam.Message)
    if err != nil {
        return err
    }
    err = dec.Decode(&pam.Signature)
    return b.Bytes(), err
}
```

**Comment by bford** [comment]
abstract.Write *should* be able to handle variable-length byte slices - if it doesn't, that's a bug.  However, abstract.Write does *not* encode the length of the slice in its output: it just writes the bytes themselves, and assumes the reader will already "know" how many bytes need to be read.

Thus, when abstract.Read tries to read a variable-length byte-slice, it expects the caller to have already allocated a slice of the correct length, and simply fills in that slice.  Thus, abstract.Write/Read should work if both the sender and receiver know the slice length ahead of time and set up a slice of exactly the correct length before calling Write and Read, respectively.  But if you leave the slice uninitialized on the receive side, abstract.Write will write a nonzero number of bytes while abstract.Read will read zero bytes, getting the sender and receiver out of sync.

Is this something different from what you're observing?

**Comment by bford** [comment]
And again, please don't use gob-encoding for protocol messages; that's a purely Go-specific encoding that we don't generally want wire-protocols to depend on.

**Comment by dyv** [comment]
The gob encoding is just a fast fix if you want to get it to a working phase. Then you can fiddle around with the specific wire-protocol that you want. The signingMessages have moved away from gob with the only exception being a test message type that we occasionally use in debugging.

We have had to hard code in the size of the buffer for wire protocols (in Unmarshalling):
```go
b := bytes.NewBuffer(data[:32])
err := abstract.Read(b, cm, nist.NewAES128SHA256P256())
rem := data[cm.C.Len():] // after secret
```

Unfortunately we have to hardcode the 32 because we cannot call cm.C.Len() if cm.C is nil. We should consider either enforcing abstract.Point.Len() not to access any of the interior fields (i.e. be fixed size) or change around the Encoding interface (if it is not fixed size we will have no way of knowing how big of a buffer to give it).

**Comment by bford** [comment]
Ugh - why not just:

P := suite.Point()
err := abstract.Read(&P)

?  Points know how to encode/decode themselves; you just need to make sure the Point object is created before the Read.  (And if you use the protobuf package with the constructors feature it'll even create Point objects for you.)

**Comment by WEB3-GForce** [comment]
Aha, I think that is the error I am having. I thought that write would fill in the byte slices for me, so I did not initialize them to any specific size. However, it is a difficult to know the size of the message and its digital signature beforehand. Since I need to send the public key as well, I'll look into using some combination of protocol buffers/ abstract.Write. Do you have any general pointers for such an approach?

Thanks for the comments Dylan; appreciate your willingness to help.

**Comment by bford** [comment]
You should be able to use your struct definition above as-is:

type PolicyApprovedMessage struct {
  PubKey abstract.Point
  Message []byte
  Signature []byte
}

To marshal a PolicyApprovedMessage struct into a Writer (e.g., a Buffer), just call:

msg := PolicyApprovedMessage{...}
buf, err := protobuf.Encode(&msg)

One way to decode is:

msg := PolicyApprovedMessage{}
msg.PubKey = suite.Point()
buf, err := protobuf.Decode(buf, &msg)

You need to create the (uninitialized) Point object here because protobuf doesn't "natively" know how to encode/decode Points but can call Encode/Decode on already-created objects that support it.

The more general approach would be to use the Constructors functionality in protobuf - i.e., give it a constructor for the Point interface - which would eliminate the need to pre-create msg.PubKey on decoding.  But the Constructors functionality is currently immature and probably needs to be refined a bit and supported better by the crypto library.

Does this help?

**Comment by jackowitzd2** [comment]
@dyv @iuliatamas As mentioned at the meeting today, following up with a more concrete example of using ```protobuf.Constructors```:
```go
var aSecret abstract.Secret
var tSecret = reflect.TypeOf(&aSecret).Elem()

var aPoint abstract.Point
var tPoint = reflect.TypeOf(&aPoint).Elem()

cons := protobuf.Constructors{
    tSecret: func() interface{} { return suite.Secret() },
    tPoint: func() interface{} { return suite.Point() },
}
```

**Comment by WEB3-GForce** [comment]
I've run into an issue using protobuf. It is not properly decoding the public key. I've tried both creating the public key before calling Decode and providing DecodeWithConstructors a constructor. The issue seems to be in this function:

func (de *decoder) putvalue(wiretype int, val reflect.Value,
	v uint64, vb []byte) error {


More specifically, when it handles interface types

	case reflect.Interface:
		// Abstract field: instantiate via dynamic constructor.
		if val.IsNil() {
			val.Set(de.instantiate(val.Type()))
		}

		// If the object support self-decoding, use that.
		if enc, ok := val.Interface().(encoding.BinaryUnmarshaler); ok {
			if wiretype != 2 {
				return errors.New(
					"bad wiretype for bytes")
			}
			return enc.UnmarshalBinary(vb)
		}

		// Decode into the object the interface points to.
		// XXX perhaps better ONLY to support self-decoding
		// for interface fields?
		return de.putvalue(wiretype, val.Elem(), v, vb)

It expects that the interface implements marshelling. abstract.Point does not. Hence, it goes to the end and tries to put the value into the object the interface points to. It realizes it can not and then reaches this code in the new function call:

	if !val.CanSet() {
		return nil
	} 

Hence, the point is not getting set. 

Is this also the case for anyone else?

**Comment by jackowitzd2** [comment]
Hmm, I'm hoping this is just an out-of-sync between your copies of protobuf and crypto - as of the changes merged earlier today ```abstract.Point``` should definitely implement ```BinaryUnmarshaler```. If that's not it, let me know and I'll have to dig further.

**Comment by WEB3-GForce** [comment]
That was the problem (needed to pull crypto). Thanks for your help! The messages seem to be working now.

@bford  I'm currently using abstract.Write when I only have cryptographic items and protobufs for more complicated structures. From a stylistic perspective, do you prefer that I always use protobufs or is this current set-up okay?

**Comment by bford** [comment]
Using abstract.Read/Write for cryptographic items is fine with me, and in fact I think preferable for cases where the fancier extensible protobuf encoding isn't needed.

**Comment by bford** [comment]
@WEB3-GForce Is this issue fully taken care of now?  If so please close this issue.

**Comment by WEB3-GForce** [comment]
It's resolved. I'll go ahead and close it.
