### ISSUE TITLE
Building Crypto library in Windows

### ISSUE THREAD

**Issue by slifland37** [DeDiS/crypto#33]
Hey all,

At the last group meeting I mentioned to Danny that I haven't actually been able to successfully build the crypto library so far, and we were both confused about the output I get when I run go test -v ./... within my local dedis/crypto repository.

Danny mentioned that I might actually be the first person trying to build the library in Windows, so I was wondering if anyone else has run into similar issues, or if anyone has an idea of what could be going wrong? Danny was particularly interested in the line I've marked with the "<---- *****" below. In particular, we're confused how the build can be failing for github.com/dedis/crypto but certain tests in subdirectories of that one are still succeeding. I just did a git pull so my repo should be in sync with the online copy.

Does anyone have any insight into what might be going on? For what it's worth, my laptop is running Windows 7 64-bit.

$ go test -v ./...
warning: GOPATH set to GOROOT (C:\Go\) has no effect
##github.com/dedis/crypto/cipher/bench
cipher\bench\cipher_test.go:10:2: cannot find package "golang.org/x/crypto/blowfish" in any of:
        C:\Go\src\golang.org\x\crypto\blowfish (from $GOROOT)
        ($GOPATH not set)
FAIL    github.com/dedis/crypto/cipher/bench [setup failed]
##github.com/dedis/crypto/test
test\cipher.go:301: undefined: cipher.Read
##github.com/dedis/crypto/openssl
realgcc.exe: warning: '-x c' after last input file has no effect                    <---- ******
realgcc.exe: no input files
FAIL    github.com/dedis/crypto [build failed]
?       github.com/dedis/crypto/abstract        [no test files]
FAIL    github.com/dedis/crypto/anon [build failed]
=== RUN TestEncode
--- PASS: TestEncode (0.00s)
=== RUN TestEncoder
--- PASS: TestEncoder (0.00s)
=== RUN TestEncoderBuffering
--- PASS: TestEncoderBuffering (0.00s)
=== RUN TestDecode
--- PASS: TestDecode (0.00s)
=== RUN TestDecoder
--- PASS: TestDecoder (0.00s)
=== RUN TestDecoderBuffering
--- PASS: TestDecoderBuffering (0.00s)
=== RUN TestDecodeCorrupt
--- PASS: TestDecodeCorrupt (0.00s)
=== RUN TestBig
--- PASS: TestBig (0.00s)
=== RUN TestNewLineCharacters
--- PASS: TestNewLineCharacters (0.00s)
=== RUN TestDecoderIssue3577
--- PASS: TestDecoderIssue3577 (0.00s)
=== RUN TestDecoderIssue4779
--- PASS: TestDecoderIssue4779 (0.00s)
=== RUN TestDecoderIssue7733
--- PASS: TestDecoderIssue7733 (0.00s)
=== RUN: ExampleEncoding_EncodeToString
--- PASS: ExampleEncoding_EncodeToString (0.00s)
=== RUN: ExampleEncoding_DecodeString
--- PASS: ExampleEncoding_DecodeString (0.00s)
=== RUN: ExampleNewEncoder
--- PASS: ExampleNewEncoder (0.00s)
PASS
ok      github.com/dedis/crypto/base64  0.189s
?       github.com/dedis/crypto/cipher  [no test files]
FAIL    github.com/dedis/crypto/cipher/aes [build failed]
?       github.com/dedis/crypto/cipher/norx     [no test files]
?       github.com/dedis/crypto/cipher/norx/check       [no test files]
=== RUN TestKeccakKats
--- PASS: TestKeccakKats (0.38s)
        sha3_test.go:95: SHA3-224
        sha3_test.go:95: SHA3-256
        sha3_test.go:95: SHA3-384
        sha3_test.go:95: SHA3-512
        sha3_test.go:95: SHAKE128
        sha3_test.go:95: SHAKE256
=== RUN TestUnalignedWrite
--- PASS: TestUnalignedWrite (0.05s)
=== RUN TestAppend
--- PASS: TestAppend (0.00s)
=== RUN TestAppendNoRealloc
--- PASS: TestAppendNoRealloc (0.00s)
=== RUN TestSqueezing
--- PASS: TestSqueezing (0.00s)
        sha3_test.go:178: SHAKE128
        sha3_test.go:178: SHAKE256
=== RUN TestReadSimulation
--- PASS: TestReadSimulation (0.00s)
PASS
ok      github.com/dedis/crypto/cipher/sha3     0.757s
?       github.com/dedis/crypto/clique  [no test files]
?       github.com/dedis/crypto/config  [no test files]
FAIL    github.com/dedis/crypto/edwards [build failed]
FAIL    github.com/dedis/crypto/edwards/ed25519 [build failed]
?       github.com/dedis/crypto/group   [no test files]
?       github.com/dedis/crypto/ints    [no test files]
?       github.com/dedis/crypto/math    [no test files]
=== RUN TestNego
Total hdrlen: 1888
--- PASS: TestNego (3.04s)
PASS
ok      github.com/dedis/crypto/nego    3.269s
FAIL    github.com/dedis/crypto/nist [build failed]
FAIL    github.com/dedis/crypto/openssl [build failed]
=== RUN TestPriPolyPick
--- PASS: TestPriPolyPick (0.00s)
=== RUN TestPriPolySecret
--- PASS: TestPriPolySecret (0.00s)
=== RUN TestPriPolyEqual
--- PASS: TestPriPolyEqual (0.00s)
=== RUN TestPriPolyAdd
--- PASS: TestPriPolyAdd (0.00s)
=== RUN TestPriPolyString
--- PASS: TestPriPolyString (0.00s)
=== RUN TestPriSharesSplitShare
--- PASS: TestPriSharesSplitShare (0.00s)
=== RUN TestPriSharesEmpty
--- PASS: TestPriSharesEmpty (0.00s)
=== RUN TestPriSharesSetShare
--- PASS: TestPriSharesSetShare (0.00s)
=== RUN TestPriSharesxCoord
--- PASS: TestPriSharesxCoord (0.00s)
=== RUN TestPriSharesSecret
--- PASS: TestPriSharesSecret (0.00s)
=== RUN TestPriSharesString
--- PASS: TestPriSharesString (0.00s)
=== RUN TestPubPolyInit
--- PASS: TestPubPolyInit (0.00s)
=== RUN TestPubPolyCommit
--- PASS: TestPubPolyCommit (1.18s)
=== RUN TestPubPolySecretCommit
--- PASS: TestPubPolySecretCommit (0.32s)
=== RUN TestPubPolyLen
--- PASS: TestPubPolyLen (0.01s)
=== RUN TestPubPolyEncodeDecode
--- PASS: TestPubPolyEncodeDecode (0.33s)
=== RUN TestPubPolyEqual
--- PASS: TestPubPolyEqual (1.34s)
=== RUN TestPubPolyAdd
--- PASS: TestPubPolyAdd (1.04s)
=== RUN TestPubPolyCheck
--- PASS: TestPubPolyCheck (0.36s)
=== RUN TestPubPolyString
--- PASS: TestPubPolyString (0.00s)
=== RUN TestPolyEval
--- PASS: TestPolyEval (0.61s)
=== RUN TestPubSharesSplitShare
--- PASS: TestPubSharesSplitShare (0.18s)
=== RUN TestPubSharesSetShare
--- PASS: TestPubSharesSetShare (0.37s)
=== RUN TestPubSharesxCoord
--- PASS: TestPubSharesxCoord (0.31s)
=== RUN TestPubSharesSecret
--- PASS: TestPubSharesSecret (0.82s)
=== RUN TestPubSharesString
--- PASS: TestPubSharesString (0.01s)
PASS
ok      github.com/dedis/crypto/poly    8.146s
FAIL    github.com/dedis/crypto/proof [build failed]
?       github.com/dedis/crypto/random  [no test files]
FAIL    github.com/dedis/crypto/shuffle [build failed]
?       github.com/dedis/crypto/subtle  [no test files]
FAIL    github.com/dedis/crypto/suites [build failed]

**Comment by bford** [comment]
Interesting - thanks for being our first Windows guinea pig. :)  

The blowfish problem is just a missing dependency; try:

    go get golang.org/x/crypto

I think sometimes when Go fetches dependences automatically, it neglects to fetch dependencies that are only in _test.go packages - perhaps that's a bit of an outstanding bug.

The realgcc.exe error is completely new to me; never seen it before.  You might go into that directory and use 'go build -x' (I think) to see what commands the Go fronted is actually running and try to figure out what is causing the error.  Is it perhaps because you don't have the openssl crypto library installed?  In any case, this shouldn't be a "fatal error" for you since nothing critical currently depends on the crypto/openssl package; it's currently used mainly for testing/benchmarking/comparison purposes.

Does this help?

**Comment by slifland37** [comment]
As a follow up, for now I'm just going to try cloning the repo onto a zoo machine and working in that environment.

So my next question is: where is Go installed on the zoo machines currently? I need to add it to my PATH to run go get, go test etc.

**Comment by bford** [comment]
I haven't tried that either; I don't know if anyone has used go in courses so far so it may not even be installed on the zoo.  You can certainly install it yourself, if that doesn't run you into quota issues.  I'd also be happy to request that it be installed on the zoo, but that may take a little while.

Another alternative, if you don't want to install a Linux partition on your Windows machine, would be to download VirtualBox and run Linux in a VM on your Windows machine.

But a third alternative is just to press ahead with running Go on Windows; it's "supposed" to work anyway. ;)  (And from your transcript it looks like it mostly was working - as I said, you can totally live without the crypto/openssl package if that's all that's breaking.)

**Comment by dyv** [comment]
You have to install it your self. Iulia and I both have it installed from source in our own directories and have experienced no issues with quota.

**Comment by bford** [comment]
@slifland37 can I get a quick status update: did you successfully get it to build and run on Windows, or drop that effort?  And please close the issue if it's no longer an issue.  Thanks.

**Comment by davidiw** [comment]
I suspect that gcc hasn't been installed. After installing go, git, mingw (64-bit), I still need to install OpenSSL and perhaps other libraries. I can't imagine that this should be the recommend method for doing this. I suspect it would be far wiser to use CygWin or WinBuild to install these packages.

**Comment by davidiw** [comment]
On further investigation, it would seem that the approach I took was the correct way, but then installing these additional libraries becomes complicated. Perhaps alternatively the build should only include native library support if gcc and the library are present. Then we could build Crypto with only install go, git, and mingw.

**Comment by slifland37** [comment]
Just to follow up, at the suggestion of David and other team members, I just installed Go on a zoo machine and was able to build with no trouble there.

So it's no longer an issue for me, but it appears that it's still an open question? Does that mean I should leave the issue open for the time being, or add it to some larger list of known bugs/feature specifications for later and then close it?

**Comment by bford** [comment]
I think it probably makes sense to use build tags on the packages like openssl that are non-essential and require external dependencies.  The "crypto/pbc" is already one such package, which uses the build tag "+build pbc".  Perhaps we should have the openssl package compiled only under a "+build openssl" tag similarly to avoid confusion?  (Was the OpenSSL dependency the main issue here or were there others?)

**Comment by davidiw** [comment]
After installing a ocmpatible mingw (gcc), I tried installing one of many
flavors of openssl, that didn't work, so I stopped. I suspect that should
be the remaining issue unless perhaps there are other similar dependencies.
I have the feeling that the remaining challenge is figuring out how to
properly install (configure) headers / libraries in windows so mingw / go
can access them.

**Comment by bford** [comment]
Sounds good, let's add an "openssl" build tag to the openssl package and call that particular problem solved. :)

If you still have that Windows-based Go install up and running and can check if it "just works" with the openssl package removed, that would be nice to know.
