### ISSUE TITLE
Insurance Blame Protocol

### ISSUE THREAD

**Issue by WEB3-GForce** [DeDiS/crypto#42]
@bford
@jackowitzd2 

I'm working on pull request #40 and I wanted to ask your advice on how to verify blame proofs. As a brief summary: 

- One server called the promiser will take out a Promise and ask several servers to act as guardians of the promise. The promise will be the private key of the promiser. The guardians will receive PriShares of the private key.

- The Promise object contains a list of all the shares encrypted with a Diffie-Hellman shared key with the appropriate guardian and the promiser.

- If the share is malformed, the guardian wants to have a way of blaming the promiser.

- To provide proof of blame, the guardian will reveal its Diffie-Hellman shared secret along with the decrypted share.

- To verify, another server will make sure that the share provided in the blame proof (when it is encrypted by the provided Diffie-Hellman shared secret) equals the entry provided in the Promise

- If the share fails to be checked by the public polynomial, the blame is justified

The issue I am having is how to verify that the Diffie-Hellman secret was constructed appropriately. Under the current setting, a malicious guardian who wanted to accuse the promiser could decrypt the Promise share using an invalid Diffie-Hellman shared secret. The result would produce a bad share, which would fail the public polynomial check. However, I would not want this case to be considered a valid blame proof.

My initial thought is to have the accuser be forced to reveal their own private key. Since the promise has the public key of the promiser, the proper Diffie-Hellman secret could then be reconstructed. I could also check whether the private key corresponds to the public key the promise has for the specific guardian. This would discourage false accusers since they would be giving away their private key and would have to get a new one.

However, the issue here is that an honest accuser has to reveal its private key even though it has done nothing wrong.

Do you have any suggestions?

**Comment by bford** [comment]
I would actually consider the Blame proof to be just one of two types of "certificates" that an insurer/guardian can generate in response to a proposed promise.  Namely, when an insurer sees a Promise, then the insurer should always create a "certificate" (e.g., PromiseCert), but the certificate can either attest that the Promise is "good" or attest that the promise is "bad".  In the former case, a PromiseCert is simply the insurer's signature on the promise.  In the latter case, a PromiseCert serves as a blame proof attesting that the Promise is bad and doubling as the insurer's digital signature on that blame proof.

To get the blame mechanism to work right, the insurer will need to reveal the Diffie-Hellman secret and prove it correct using the zero-knowledge proof facilities provided by the 'crypto/proof' package.  In particular, let A = aG be the short-term DH public key shared by the promise, and let B = bG be the insurer's (long-term) public key.  The DH secret is S=abG, which the insurer computes as S = bA.  In a blame proof, the insurer will reveal S, and also use the crypto/proof package to provide a proof that it used the same private secret 'b' to form S from A as the 'b' it used to form B (its own public key) from G (the well-known generator/base-point).  Make sense?

However, to make these blame proofs "safe" for insurers to make, the Promise itself will also need to contain a zero-knowledge proof as well: namely, the promiser will need to prove knowledge of the short-term private key it is sharing (i.e., prove knowledge of the 'a' above), and the insurers will need to check that knowledge proof *before* producing a "promise certificate" of any kind (either "good" or "bad").  A Promise without a valid zero-knowledge proof will simply be self-evidently invalid (just as if it were syntactically invalid), and should not be accepted by anyone (e.g., promise.BinaryUnmarshal should check the zero-knowledge proof and fail the unmarshal if the proof check fails).

Does this help?

**Comment by WEB3-GForce** [comment]
@bford 

It does. I've implemented a good part of it but have run into an issue concernng the zero-knowledge proofs of the promiser.

Currently (please see pull request #40 for code), the promise secret shares are constructed and stored as follows:

    1) Diffie-Hellman Shared-Secret = Mul(promiser.PrivateKey, insurer.PublicKey)
    2) fresh_secret = PickNewSecret(Diffie-Hellman Shared_Secret)
    3) final_secret = fresh_secret + secret_share

final_secret is what I store in an array within the promise. It is what other clients will see when they receive the promise.

I'm having difficulty constructing a crypto/proof that verifies final_secret was constructed successfully. Most proof examples I have seen are of the form:

      Point = some_combination_of_secrets

rather than of the form:

      Secret = combination_of_other_secrets

Do you happen to know how I could construct a proof that could work?

While I could provide a zero knowledge proof that the promiser knew the private key for the Diffie-Hellman secret, it would have the following short-comings:

    (1) A client would need to know the Diffie-Hellman shared secret to verify this
    (2) If the client did know the shared secret, it could instead verify by decrypting
       final_secret to get the secret share. Then, the client could just make sure that
       the share passed the public polynomial check.

Alternatively, we could exclude the zero-proof from the promise and rely on good insurers to be "whistleblowers" if they detect a malformed share.
