### ISSUE TITLE
Add response exception handling/mechanism to cosi

### ISSUE THREAD

**Issue by Liamsi** [dedis/crypto#76]
In the current [libcosi](https://github.com/dedis/crypto/tree/libcosi) branch there is no possibility for nodes to raise an exception in the response phase. 

To the cosi package we want to add two new functions which can create a response and signature with exceptions (maybe `ResponseException` and `SignatureException`). 
`VerifySignature` needs to be modified so that it can handle both signatures: those created by the current  `Signature` func. and the to be created `SignatureExcpetion` func. The difference between both signatures is that the first creates a signature of the form `Comm || Resp || mask` and the second creates one of the form `Comm || Resp || mask || AggCommit`. 

Make it clear in the documentation which functions and how they are (not) compatible to each other.

**Comment by Liamsi** [comment]
Either will be merged against #75 or to development (depending on if #75 gets merged first or not)

**Comment by ineiti** [comment]
Can you add a PR?

**Comment by Liamsi** [comment]
I didn't push yet as the signature verification still fails. But sure I can
still do a PR if you want to have a look...
Am 16.06.2016 9:21 vorm. schrieb "Linus Gasser" <notifications@github.com>:

Can you add a PR?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/dedis/crypto/issues/76#issuecomment-226407481>, or mute
the thread
<https://github.com/notifications/unsubscribe/AHGNZimyMl15JqFwWLoSn0qWikwXPvj1ks5qMPl2gaJpZM4I1IqE>
.

**Comment by Liamsi** [comment]
As we discussed this isn't something we would want to implement in `crypto` yet but instead in `cothority` as it will get used in BftCosi. Will open an issue in cothority and later delete the branch response_exception later.
