### ISSUE TITLE
Clone is not working on Scalars

### ISSUE THREAD

**Issue by ineiti** [dedis/crypto#88]
`Scalar.Clone` is not copying all data.

**Comment by nikkolasg** [comment]
The title and the description of the issue are two differents subjects to me. 
We should first fix the PR https://github.com/dedis/crypto/pull/87 and then talk about inconsistencies in nist.Int.
I prefer your first proposition, but without 
> all New*-methods should take a ByteOrder

I'm not sure ByteOrder should be mandatory, as long as it keeps fixed.
